/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk.ui;

import java.awt.Color;
import java.awt.List;
import java.sql.Connection;
import javax.swing.JPanel;
import spk.data.Auth;
import spk.data.Koneksi;
import spk.data.Pengguna;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import spk.data.Kriteria;
import javax.swing.table.DefaultTableModel;
import spk.data.Grup;
/**
 *
 * @author MOTHAFUCKAS
 */
public class Admin extends javax.swing.JFrame {
    private Connection con;
    private Statement stt;
    private ResultSet rss;
    private Pengguna User =  new Pengguna();
    private Grup grup = new Grup();
    private DefaultTableModel model;
    Pengguna pengguna = Auth.penggunaLogin();
    Kriteria kriteria = new Kriteria();
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        String nama = pengguna.getNama();
        welcomeText.setText("Hai, " + nama);
        
        setColor(menu_pengguna);
        pengguna_aktif.setOpaque(true);
        resetColor(new JPanel[]{menu_grup}, new JPanel[]{grup_aktif});        
        resetColor(new JPanel[]{menu_varietas}, new JPanel[]{varietas_aktif});
        panel_pengguna.setVisible(true);
        panel_grup.setVisible(false);
        panel_varietas.setVisible(false);
        JDialog.setDefaultLookAndFeelDecorated(true);
        
    }

    private void InitTablePengguna() {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Asal Daerah");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Role");
        TablePengguna.setModel(model);
        TablePengguna.removeColumn(TablePengguna.getColumnModel().getColumn(0));
    }
    
    
    private void TampilDataPengguna() {
        ArrayList<Pengguna> user = User.allPengguna();
        try {
            for (int i = 0; i < user.size(); i++) {
                Object[] record = new Object[6];
                record[0]=user.get(i).getId();                
                record[1]=user.get(i).getNama();
                record[2]=user.get(i).getAsalDaerah();
                record[3]=user.get(i).getUsername();
                record[4]=user.get(i).getPassword();
                record[5]=user.get(i).getRole();
                
                model.addRow(record);
            }
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }        
    }
    
    private void InitTableGrup() {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        TableGrup.setModel(model);
        TableGrup.removeColumn(TableGrup.getColumnModel().getColumn(0));
    }
    
    private void TampilDataGrup() {
        ArrayList<Grup> group = grup.allGrup();
        try {
            for (int i = 0; i < group.size(); i++) {
                Object[] record = new Object[6];
                record[0]=group.get(i).getId();                
                record[1]=group.get(i).getNama();
                model.addRow(record);
            }
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }        
    }
    
    private void setColor(JPanel panel) {
        panel.setBackground(new Color(41, 57, 60));
    }
    
    private void resetColor(JPanel[] panel, JPanel[] indicators) {
        for (int i = 0; i < panel.length; i++) {
            panel[i].setBackground(new Color(23, 35, 51));
        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_bar = new javax.swing.JPanel();
        menu_grup = new javax.swing.JPanel();
        grup_aktif = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu_pengguna = new javax.swing.JPanel();
        pengguna_aktif = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu_varietas = new javax.swing.JPanel();
        varietas_aktif = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContainerPanel = new javax.swing.JPanel();
        panel_varietas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_pengguna = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namaPengguna = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        asalDaerahPengguna = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        usernamePengguna = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        passwordPengguna = new javax.swing.JTextField();
        rolePengguna = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePengguna = new javax.swing.JTable();
        SimpanPengguna = new javax.swing.JButton();
        UpdatePengguna = new javax.swing.JButton();
        HapusPengguna = new javax.swing.JButton();
        ResetPengguna = new javax.swing.JButton();
        panel_grup = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NamaGrup = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SimpanGrup = new javax.swing.JButton();
        UpdateGrup = new javax.swing.JButton();
        HapusGrup = new javax.swing.JButton();
        ResetGrup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableGrup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_bar.setBackground(new java.awt.Color(23, 35, 51));
        side_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_grup.setBackground(new java.awt.Color(23, 35, 51));
        menu_grup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_grupMousePressed(evt);
            }
        });

        grup_aktif.setOpaque(false);
        grup_aktif.setPreferredSize(new java.awt.Dimension(5, 40));

        javax.swing.GroupLayout grup_aktifLayout = new javax.swing.GroupLayout(grup_aktif);
        grup_aktif.setLayout(grup_aktifLayout);
        grup_aktifLayout.setHorizontalGroup(
            grup_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        grup_aktifLayout.setVerticalGroup(
            grup_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Grup");

        javax.swing.GroupLayout menu_grupLayout = new javax.swing.GroupLayout(menu_grup);
        menu_grup.setLayout(menu_grupLayout);
        menu_grupLayout.setHorizontalGroup(
            menu_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_grupLayout.createSequentialGroup()
                .addComponent(grup_aktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        menu_grupLayout.setVerticalGroup(
            menu_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grup_aktif, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addGroup(menu_grupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_bar.add(menu_grup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, -1));

        menu_pengguna.setBackground(new java.awt.Color(41, 57, 80));
        menu_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_penggunaMousePressed(evt);
            }
        });

        pengguna_aktif.setPreferredSize(new java.awt.Dimension(5, 40));

        javax.swing.GroupLayout pengguna_aktifLayout = new javax.swing.GroupLayout(pengguna_aktif);
        pengguna_aktif.setLayout(pengguna_aktifLayout);
        pengguna_aktifLayout.setHorizontalGroup(
            pengguna_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pengguna_aktifLayout.setVerticalGroup(
            pengguna_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengguna");

        javax.swing.GroupLayout menu_penggunaLayout = new javax.swing.GroupLayout(menu_pengguna);
        menu_pengguna.setLayout(menu_penggunaLayout);
        menu_penggunaLayout.setHorizontalGroup(
            menu_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_penggunaLayout.createSequentialGroup()
                .addComponent(pengguna_aktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addGap(0, 74, Short.MAX_VALUE))
        );
        menu_penggunaLayout.setVerticalGroup(
            menu_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pengguna_aktif, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addGroup(menu_penggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_bar.add(menu_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, 210, -1));

        menu_varietas.setBackground(new java.awt.Color(23, 35, 51));
        menu_varietas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_varietasMousePressed(evt);
            }
        });

        varietas_aktif.setOpaque(false);
        varietas_aktif.setPreferredSize(new java.awt.Dimension(5, 40));

        javax.swing.GroupLayout varietas_aktifLayout = new javax.swing.GroupLayout(varietas_aktif);
        varietas_aktif.setLayout(varietas_aktifLayout);
        varietas_aktifLayout.setHorizontalGroup(
            varietas_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        varietas_aktifLayout.setVerticalGroup(
            varietas_aktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Varietas");

        javax.swing.GroupLayout menu_varietasLayout = new javax.swing.GroupLayout(menu_varietas);
        menu_varietas.setLayout(menu_varietasLayout);
        menu_varietasLayout.setHorizontalGroup(
            menu_varietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_varietasLayout.createSequentialGroup()
                .addComponent(varietas_aktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        menu_varietasLayout.setVerticalGroup(
            menu_varietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(varietas_aktif, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addGroup(menu_varietasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_bar.add(menu_varietas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, -1));

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Hai, ");
        side_bar.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kButton1.setBorder(null);
        kButton1.setText("LOGOUT");
        kButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        kButton1.setkStartColor(new java.awt.Color(0, 51, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        side_bar.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 150, 40));

        getContentPane().add(side_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 670));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(944, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 980, 50));

        ContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContainerPanel.setLayout(new java.awt.CardLayout());

        panel_varietas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Varietas");
        jLabel7.setFocusable(false);

        javax.swing.GroupLayout panel_varietasLayout = new javax.swing.GroupLayout(panel_varietas);
        panel_varietas.setLayout(panel_varietasLayout);
        panel_varietasLayout.setHorizontalGroup(
            panel_varietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_varietasLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel7)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        panel_varietasLayout.setVerticalGroup(
            panel_varietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_varietasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(581, Short.MAX_VALUE))
        );

        ContainerPanel.add(panel_varietas, "card2");

        panel_pengguna.setBackground(new java.awt.Color(204, 204, 204));
        panel_pengguna.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_penggunaComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengguna");
        jLabel5.setFocusable(false);

        jLabel8.setText("Deskripsi");

        jLabel9.setText("Nama");

        jLabel10.setText("Asal Daerah");

        jLabel11.setText("Username");

        usernamePengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamePenggunaActionPerformed(evt);
            }
        });

        jLabel12.setText("Password");

        jLabel13.setText("Role");

        rolePengguna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pengguna" }));
        rolePengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolePenggunaActionPerformed(evt);
            }
        });

        TablePengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePengguna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablePengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePengguna);

        SimpanPengguna.setText("Simpan");
        SimpanPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPenggunaActionPerformed(evt);
            }
        });

        UpdatePengguna.setText("Update");
        UpdatePengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePenggunaActionPerformed(evt);
            }
        });

        HapusPengguna.setText("Hapus");
        HapusPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPenggunaActionPerformed(evt);
            }
        });

        ResetPengguna.setText("Reset");
        ResetPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPenggunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_penggunaLayout = new javax.swing.GroupLayout(panel_pengguna);
        panel_pengguna.setLayout(panel_penggunaLayout);
        panel_penggunaLayout.setHorizontalGroup(
            panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penggunaLayout.createSequentialGroup()
                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_penggunaLayout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel5))
                    .addGroup(panel_penggunaLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel8))
                    .addGroup(panel_penggunaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_penggunaLayout.createSequentialGroup()
                                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(asalDaerahPengguna)
                                    .addComponent(rolePengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel_penggunaLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(usernamePengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_penggunaLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(passwordPengguna))))
                            .addGroup(panel_penggunaLayout.createSequentialGroup()
                                .addComponent(SimpanPengguna)
                                .addGap(40, 40, 40)
                                .addComponent(UpdatePengguna)
                                .addGap(65, 65, 65)
                                .addComponent(HapusPengguna)
                                .addGap(31, 31, 31)
                                .addComponent(ResetPengguna)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        panel_penggunaLayout.setVerticalGroup(
            panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(namaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(usernamePengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(asalDaerahPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(passwordPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(rolePengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(panel_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanPengguna)
                    .addComponent(UpdatePengguna)
                    .addComponent(HapusPengguna)
                    .addComponent(ResetPengguna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        ContainerPanel.add(panel_pengguna, "card2");

        panel_grup.setBackground(new java.awt.Color(204, 204, 204));
        panel_grup.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_grupComponentShown(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Grup");
        jLabel6.setFocusable(false);

        jLabel14.setText("Nama");

        jLabel15.setText("Deskripsi");

        SimpanGrup.setText("Simpan");
        SimpanGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanGrupActionPerformed(evt);
            }
        });

        UpdateGrup.setText("Update");
        UpdateGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateGrupActionPerformed(evt);
            }
        });

        HapusGrup.setText("Hapus");
        HapusGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusGrupActionPerformed(evt);
            }
        });

        ResetGrup.setText("Reset");
        ResetGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetGrupActionPerformed(evt);
            }
        });

        TableGrup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableGrup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableGrup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGrupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableGrup);

        javax.swing.GroupLayout panel_grupLayout = new javax.swing.GroupLayout(panel_grup);
        panel_grup.setLayout(panel_grupLayout);
        panel_grupLayout.setHorizontalGroup(
            panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_grupLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(414, 414, 414))
            .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_grupLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_grupLayout.createSequentialGroup()
                            .addGap(327, 327, 327)
                            .addComponent(jLabel15))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_grupLayout.createSequentialGroup()
                            .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SimpanGrup)
                                .addComponent(jLabel14))
                            .addGap(40, 40, 40)
                            .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NamaGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_grupLayout.createSequentialGroup()
                                    .addComponent(UpdateGrup)
                                    .addGap(65, 65, 65)
                                    .addComponent(HapusGrup)
                                    .addGap(31, 31, 31)
                                    .addComponent(ResetGrup)))))
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        panel_grupLayout.setVerticalGroup(
            panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_grupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(581, Short.MAX_VALUE))
            .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_grupLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel15)
                    .addGap(45, 45, 45)
                    .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(NamaGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(150, 150, 150)
                    .addGroup(panel_grupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SimpanGrup)
                        .addComponent(UpdateGrup)
                        .addComponent(HapusGrup)
                        .addComponent(ResetGrup))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        ContainerPanel.add(panel_grup, "card2");

        getContentPane().add(ContainerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 900, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_grupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_grupMousePressed
       setColor(menu_grup);
        grup_aktif.setOpaque(true);
        resetColor(new JPanel[]{menu_pengguna}, new JPanel[]{pengguna_aktif});        
        resetColor(new JPanel[]{menu_varietas}, new JPanel[]{varietas_aktif});
        panel_pengguna.setVisible(false);
        panel_grup.setVisible(true);
        panel_varietas.setVisible(false);
    }//GEN-LAST:event_menu_grupMousePressed

    private void menu_penggunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penggunaMousePressed
        setColor(menu_pengguna);
        pengguna_aktif.setOpaque(true);
        resetColor(new JPanel[]{menu_grup}, new JPanel[]{grup_aktif});        
        resetColor(new JPanel[]{menu_varietas}, new JPanel[]{varietas_aktif});
        panel_pengguna.setVisible(true);
        panel_grup.setVisible(false);
        panel_varietas.setVisible(false);
    }//GEN-LAST:event_menu_penggunaMousePressed

    private void menu_varietasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_varietasMousePressed
        setColor(menu_varietas);
        varietas_aktif.setOpaque(true);
        resetColor(new JPanel[]{menu_grup}, new JPanel[]{grup_aktif});        
        resetColor(new JPanel[]{menu_pengguna}, new JPanel[]{pengguna_aktif});
        panel_pengguna.setVisible(false);
        panel_grup.setVisible(false);
        panel_varietas.setVisible(true);
    }//GEN-LAST:event_menu_varietasMousePressed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        Auth.logout(pengguna.getId());
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void usernamePenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamePenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamePenggunaActionPerformed

    private void panel_penggunaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_penggunaComponentShown
     InitTablePengguna();
     TampilDataPengguna();
    }//GEN-LAST:event_panel_penggunaComponentShown

    private void rolePenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolePenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolePenggunaActionPerformed

    private void SimpanPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPenggunaActionPerformed
        String nama = namaPengguna.getText();
        String asal = asalDaerahPengguna.getText();
        String username = usernamePengguna.getText();
        String password = passwordPengguna.getText();
        String role = rolePengguna.getSelectedItem().toString();
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menyimpan Pengguna ?", "Simpan Pengguna",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Menyimpan Pengguna");
        } else if (response == JOptionPane.YES_OPTION) {
            if (User.tambah(username, password, nama, asal, role)) {
                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Pengguna");
                InitTablePengguna();
                TampilDataPengguna();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
        
    }//GEN-LAST:event_SimpanPenggunaActionPerformed

    private void TablePenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePenggunaMouseClicked
       int row = TablePengguna.getSelectedRow();
       namaPengguna.setText(TablePengguna.getValueAt(row,0).toString());
       asalDaerahPengguna.setText(TablePengguna.getValueAt(row,1).toString());
       usernamePengguna.setText(TablePengguna.getValueAt(row,2).toString());
       passwordPengguna.setText(TablePengguna.getValueAt(row,3).toString());
       rolePengguna.getModel().setSelectedItem(TablePengguna.getValueAt(row,4).toString());
    }//GEN-LAST:event_TablePenggunaMouseClicked

    private void UpdatePenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePenggunaActionPerformed
        String nama = namaPengguna.getText();
        String asal = asalDaerahPengguna.getText();
        String username = usernamePengguna.getText();
        String password = passwordPengguna.getText();
        String role = rolePengguna.getSelectedItem().toString();
        
        int row = TablePengguna.getSelectedRow();
        int id = Integer.parseInt(TablePengguna.getModel().getValueAt(row,0).toString());
        
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah Pengguna ?", "Ubah Pengguna",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Mengubah Pengguna");
        } else if (response == JOptionPane.YES_OPTION) {
            if (User.ubah(id, username, nama, asal, role)) {
                JOptionPane.showMessageDialog(null, "Berhasil Mengubah Pengguna");
                InitTablePengguna();
                TampilDataPengguna();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
    }//GEN-LAST:event_UpdatePenggunaActionPerformed

    private void HapusPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPenggunaActionPerformed
        int row = TablePengguna.getSelectedRow();
        int id = Integer.parseInt(TablePengguna.getModel().getValueAt(row,0).toString());
        
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus Pengguna ?", "hapus Pengguna",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Menghapus Pengguna");
        } else if (response == JOptionPane.YES_OPTION) {
            if (User.hapus(id)) {
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Pengguna");
                InitTablePengguna();
                TampilDataPengguna();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
   
    }//GEN-LAST:event_HapusPenggunaActionPerformed

    private void ResetPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPenggunaActionPerformed
        namaPengguna.setText("");
       asalDaerahPengguna.setText("");
       usernamePengguna.setText("");
       passwordPengguna.setText("");
       rolePengguna.setSelectedItem("");
    }//GEN-LAST:event_ResetPenggunaActionPerformed

    private void UpdateGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateGrupActionPerformed
        String nama = NamaGrup.getText();
        
        
        int row = TableGrup.getSelectedRow();
        int id = Integer.parseInt(TableGrup.getModel().getValueAt(row,0).toString());
        
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah Grup ?", "Ubah Grup",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Mengubah Grup");
        } else if (response == JOptionPane.YES_OPTION) {
            if (grup.ubah(id, nama)) {
                JOptionPane.showMessageDialog(null, "Berhasil Mengubah Grup");
                InitTableGrup();
                TampilDataGrup();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
    }//GEN-LAST:event_UpdateGrupActionPerformed

    private void HapusGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusGrupActionPerformed
        int row = TableGrup.getSelectedRow();
        int id = Integer.parseInt(TableGrup.getModel().getValueAt(row,0).toString());
        
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus Grup ?", "hapus Grup",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Menghapus Grup");
        } else if (response == JOptionPane.YES_OPTION) {
            if (grup.hapus(id)) {
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Grup");
                InitTableGrup();
                TampilDataGrup();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
    }//GEN-LAST:event_HapusGrupActionPerformed

    private void ResetGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetGrupActionPerformed
        NamaGrup.setText("");
    }//GEN-LAST:event_ResetGrupActionPerformed

    private void TableGrupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGrupMouseClicked
        int row = TableGrup.getSelectedRow();
       NamaGrup.setText(TableGrup.getValueAt(row,0).toString());
       
    }//GEN-LAST:event_TableGrupMouseClicked

    private void panel_grupComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_grupComponentShown
        InitTableGrup();
        TampilDataGrup();
    }//GEN-LAST:event_panel_grupComponentShown

    private void SimpanGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanGrupActionPerformed
       String nama = NamaGrup.getText();
        
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menyimpan Grup ?", "Simpan Grup",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Batal Menyimpan Grup");
        } else if (response == JOptionPane.YES_OPTION) {
            if (grup.tambah(nama)) {
                JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Grup");
                InitTableGrup();
                TampilDataGrup();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
    }//GEN-LAST:event_SimpanGrupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JButton HapusGrup;
    private javax.swing.JButton HapusPengguna;
    private javax.swing.JTextField NamaGrup;
    private javax.swing.JButton ResetGrup;
    private javax.swing.JButton ResetPengguna;
    private javax.swing.JButton SimpanGrup;
    private javax.swing.JButton SimpanPengguna;
    private javax.swing.JTable TableGrup;
    private javax.swing.JTable TablePengguna;
    private javax.swing.JButton UpdateGrup;
    private javax.swing.JButton UpdatePengguna;
    private javax.swing.JTextField asalDaerahPengguna;
    private javax.swing.JPanel grup_aktif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton1;
    private javax.swing.JPanel menu_grup;
    private javax.swing.JPanel menu_pengguna;
    private javax.swing.JPanel menu_varietas;
    private javax.swing.JTextField namaPengguna;
    private javax.swing.JPanel panel_grup;
    private javax.swing.JPanel panel_pengguna;
    private javax.swing.JPanel panel_varietas;
    private javax.swing.JTextField passwordPengguna;
    private javax.swing.JPanel pengguna_aktif;
    private javax.swing.JComboBox<String> rolePengguna;
    private javax.swing.JPanel side_bar;
    private javax.swing.JTextField usernamePengguna;
    private javax.swing.JPanel varietas_aktif;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
