/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spk.ui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import spk.data.Auth;
import spk.data.Koneksi;
import spk.data.Pengguna;

/**
 *
 * @author anas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private final Connection con;
    public Login() {
        
        con = Koneksi.getkoneksi();
//        if (con != null) {
//            initComponents();
//        }else{
//            System.exit(0);
//        }
//        initComponents();
           login("admin","123123");
    }
    
    private void login(String username,String password){
        Pengguna penggunaLogin =Auth.login(username, password);
        if(penggunaLogin != null){
           if(Auth.ubahStatusLogin(penggunaLogin.getId())){
                    Home home = new Home();
                    home.setPenggunaLogin(penggunaLogin);
                    home.setVisible(true);
            } 
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Login Gagal Periksa Username, Password dan Status Anda","Perhatian",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_daftar = new javax.swing.JLabel();
        title_masuk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg_daftar = new javax.swing.JLabel();
        bg_masuk = new javax.swing.JLabel();
        pohon_sawit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_daftar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        title_daftar.setForeground(new java.awt.Color(71, 120, 197));
        title_daftar.setText("Daftar");
        jPanel1.add(title_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 37, -1, -1));

        title_masuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        title_masuk.setForeground(new java.awt.Color(255, 255, 255));
        title_masuk.setText("Masuk");
        jPanel1.add(title_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        bg_daftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg_btn_daftar.png"))); // NOI18N
        jPanel1.add(bg_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 21, 120, 50));

        bg_masuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg_btn_masuk.png"))); // NOI18N
        jPanel1.add(bg_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        pohon_sawit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/pohon.png"))); // NOI18N
        jPanel1.add(pohon_sawit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 360, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_daftar;
    private javax.swing.JLabel bg_masuk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pohon_sawit;
    private javax.swing.JLabel title_daftar;
    private javax.swing.JLabel title_masuk;
    // End of variables declaration//GEN-END:variables

    
}
